### ISSUE TITLE
Como incluir el servicio?

### ISSUE THREAD

**Issue by braianj** [smsc/smsc-api-php#4]
Hola estoy intentando utilizar el servicio, pero me pide que incluya el servicio, como hay que hacer? y se puede agregar al readme.MD para futuros usuario?

> Attempted to load class "Smsc" from namespace "smsc".
> Did you forget a "use" statement for another namespace?

**Comment by pablorsk** [comment]
Hi @braianj,

On the future, we can put namespaces. SMSC library, right now, don't support namespace. Just use `\SMSC` for now.

**Comment by mariobigboy** [comment]
Hola Pablo, tengo problemas para instalar con composer, cuando intento correr me tira el siguiente error:
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
zero@:/opt/lampp/htdocs/sms
sabes a que puede deberse??

**Comment by pablorsk** [comment]
@mariobigboy parece ser algo relacionado a que te falta activar alguna librería en el sistema, de tu proyecto. SMSC no requiere nada raro, solo PHP >= 5.2. Así que debe ser otra librería de tu composer.
